server:
  port: 0
spring:
  application:
    name: plan-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    properties:
      hibernate:
        show_sql: ${JPA_SHOW_SQL:false}
        format_sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id:
      ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
