spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false # Spring Kafka가 리스너 처리 성공 후 커밋
      auto-offset-reset: earliest # offset이 없을때 어디서 부터 읽을지 설정


    listener:
      ack-mode: record # 메시지 처리할때마다 commit